version: "3"
services:
  conveer_test:
    container_name: conveer_test
    image: ultralytics/yolov5:latest
    volumes:
      - ../:/usr/src/app
      - ../model_forge:/usr/src/app/model_forge
    working_dir: /usr/src
    shm_size: 8gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: "no"
    # command: ["python3", "app/train.py"]
    command: ["sleep", "infinity"]
    # command: ["python3", "-m", "yolov5_refactor.train", "--weights yolov5_refactor/yolov5s_mod.pt"]
    # command: bash -c "python3 -m app.train --weights ..."
